import type { MissingCase, Sighting } from "@/lib/types";

export const provinces = [
  "Distrito Nacional",
  "Santo Domingo",
  "Santiago",
  "La Vega",
  "Puerto Plata",
  "San Cristobal",
  "Duarte",
  "La Altagracia",
  "San Pedro de Macoris",
  "Barahona"
];

export const demoCases: MissingCase[] = [
  {
    id: "case-001",
    slug: "maria-fernanda-rojas",
    full_name: "Maria Fernanda Rojas",
    nickname: "Mafer",
    age: 16,
    gender: "female",
    height: "5'3\"",
    photo_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",
    province: "Distrito Nacional",
    municipality: "Santo Domingo de Guzman",
    location_last_seen: "Avenida Winston Churchill, cerca de una parada de autobus",
    date_last_seen: "2026-04-27",
    time_last_seen: "18:20",
    clothing_description: "Polo blanco, jeans azul oscuro y tenis negros.",
    physical_traits: "Cabello castano largo, lunar pequeno en la mejilla izquierda.",
    circumstances: "Salio de clases y no regreso a casa. Su telefono dejo de responder esa noche.",
    contact_name: "Equipo Echo RD",
    contact_phone: "+1 809 000 0000",
    whatsapp: "+18090000000",
    email: "ayuda@echord.do",
    police_report: true,
    urgency_level: "critical",
    status: "urgent",
    verified: true,
    demo: true,
    created_at: "2026-04-28T10:30:00Z",
    updated_at: "2026-04-29T12:00:00Z"
  },
  {
    id: "case-002",
    slug: "jose-antonio-matos",
    full_name: "Jose Antonio Matos",
    nickname: "Tony",
    age: 72,
    gender: "male",
    height: "5'7\"",
    photo_url: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&w=900&q=80",
    province: "Santiago",
    municipality: "Santiago de los Caballeros",
    location_last_seen: "Sector Los Jardines Metropolitanos",
    date_last_seen: "2026-04-25",
    time_last_seen: "09:10",
    clothing_description: "Camisa azul clara, pantalon caqui y gorra gris.",
    physical_traits: "Usa lentes, camina con baston, barba blanca corta.",
    circumstances: "Fue visto caminando hacia una farmacia y no regreso.",
    contact_name: "Equipo Echo RD",
    contact_phone: "+1 809 000 0000",
    whatsapp: "+18090000000",
    email: "ayuda@echord.do",
    police_report: true,
    urgency_level: "high",
    status: "active",
    verified: true,
    demo: true,
    created_at: "2026-04-26T15:00:00Z",
    updated_at: "2026-04-27T08:00:00Z"
  },
  {
    id: "case-003",
    slug: "luis-alberto-pena",
    full_name: "Luis Alberto Pena",
    nickname: "Beto",
    age: 24,
    gender: "male",
    height: "5'10\"",
    photo_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=80",
    province: "La Vega",
    municipality: "Constanza",
    location_last_seen: "Carretera hacia Jarabacoa",
    date_last_seen: "2026-04-22",
    time_last_seen: "21:45",
    clothing_description: "Abrigo negro, camiseta roja y tenis blancos.",
    physical_traits: "Tatuaje pequeno en el antebrazo derecho.",
    circumstances: "Ultima comunicacion por mensaje indicando que esperaba transporte.",
    contact_name: "Equipo Echo RD",
    contact_phone: "+1 809 000 0000",
    whatsapp: "+18090000000",
    email: "ayuda@echord.do",
    police_report: false,
    urgency_level: "standard",
    status: "active",
    verified: true,
    demo: true,
    created_at: "2026-04-23T17:20:00Z",
    updated_at: "2026-04-24T10:15:00Z"
  },
  {
    id: "case-004",
    slug: "ana-sofia-reyes",
    full_name: "Ana Sofia Reyes",
    nickname: "Sofi",
    age: 9,
    gender: "female",
    height: "4'4\"",
    photo_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=900&q=80",
    province: "Santo Domingo",
    municipality: "Santo Domingo Este",
    location_last_seen: "Parque del Este",
    date_last_seen: "2026-04-30",
    time_last_seen: "16:05",
    clothing_description: "Vestido amarillo, sandalias rosadas y mochila morada.",
    physical_traits: "Cabello rizado, cicatriz pequena sobre la ceja derecha.",
    circumstances: "Se separo de su familiar durante una actividad comunitaria.",
    contact_name: "Equipo Echo RD",
    contact_phone: "+1 809 000 0000",
    whatsapp: "+18090000000",
    email: "ayuda@echord.do",
    police_report: true,
    urgency_level: "critical",
    status: "urgent",
    verified: true,
    demo: true,
    created_at: "2026-04-30T22:10:00Z",
    updated_at: "2026-05-01T01:00:00Z"
  },
  {
    id: "case-005",
    slug: "carmen-elena-duarte",
    full_name: "Carmen Elena Duarte",
    nickname: "Carmencita",
    age: 41,
    gender: "female",
    height: "5'5\"",
    photo_url: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=900&q=80",
    province: "Puerto Plata",
    municipality: "Sosua",
    location_last_seen: "Terminal de transporte publico",
    date_last_seen: "2026-04-19",
    time_last_seen: "13:30",
    clothing_description: "Blusa verde, pantalon negro y cartera marron.",
    physical_traits: "Cabello negro hasta los hombros, usa pulsera medica.",
    circumstances: "Tenia cita medica y no llego al centro de salud.",
    contact_name: "Equipo Echo RD",
    contact_phone: "+1 809 000 0000",
    whatsapp: "+18090000000",
    email: "ayuda@echord.do",
    police_report: true,
    urgency_level: "high",
    status: "active",
    verified: true,
    demo: true,
    created_at: "2026-04-20T11:40:00Z",
    updated_at: "2026-04-21T13:00:00Z"
  },
  {
    id: "case-006",
    slug: "ricardo-manuel-santos",
    full_name: "Ricardo Manuel Santos",
    nickname: "Ricky",
    age: 31,
    gender: "male",
    height: "6'0\"",
    photo_url: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=900&q=80",
    province: "San Cristobal",
    municipality: "Bajos de Haina",
    location_last_seen: "Zona franca de Haina",
    date_last_seen: "2026-03-28",
    time_last_seen: "07:50",
    clothing_description: "Uniforme de trabajo azul marino y botas negras.",
    physical_traits: "Complexion atletica, cicatriz en la mano izquierda.",
    circumstances: "Caso resuelto tras aviso ciudadano validado por familiares.",
    contact_name: "Equipo Echo RD",
    contact_phone: "+1 809 000 0000",
    whatsapp: "+18090000000",
    email: "ayuda@echord.do",
    police_report: true,
    urgency_level: "standard",
    status: "found_safe",
    verified: true,
    demo: true,
    created_at: "2026-03-29T09:15:00Z",
    updated_at: "2026-04-02T17:00:00Z"
  }
];

export const demoSightings: Sighting[] = [
  {
    id: "sighting-001",
    case_id: "case-001",
    location_text: "Parada cerca de Agora Mall",
    province: "Distrito Nacional",
    date_seen: "2026-04-28",
    time_seen: "19:15",
    description: "Persona parecida esperando transporte, parecia nerviosa.",
    image_url: "",
    video_url: "",
    external_link: "",
    maps_link: "https://maps.google.com",
    anonymous: false,
    priority: "high",
    status: "reviewing",
    created_at: "2026-04-28T23:10:00Z"
  },
  {
    id: "sighting-002",
    case_id: "case-004",
    location_text: "Entrada del parque",
    province: "Santo Domingo",
    date_seen: "2026-04-30",
    time_seen: "16:30",
    description: "Reporte recibido con posible coincidencia de ropa.",
    image_url: "private://sightings/demo-image.jpg",
    video_url: "",
    external_link: "",
    maps_link: "",
    anonymous: true,
    priority: "high",
    status: "new",
    created_at: "2026-04-30T23:50:00Z"
  }
];

export const resources = [
  { title: "Sistema Nacional de Atencion a Emergencias", description: "Emergencias y asistencia inmediata.", phone: "911", website: "https://911.gob.do", category: "Emergencia" },
  { title: "Policia Nacional", description: "Reporte formal y seguimiento institucional.", phone: "809-682-2151", website: "https://policianacional.gob.do", category: "Autoridad" },
  { title: "Linea Vida", description: "Apoyo emocional y orientacion en crisis.", phone: "*462", website: "https://msp.gob.do", category: "Apoyo" }
];

export function getCaseBySlug(slug: string) {
  return demoCases.find((item) => item.slug === slug);
}

export function publicCases() {
  return demoCases.filter((item) => ["active", "urgent", "found_safe"].includes(item.status));
}
